### ISSUE TITLE
PrePostDeploymentScript fails to convert json on pipeline parameter of bool type

### ISSUE THREAD

**Issue by nwcm** [Azure/Azure-DataFactory#510]
```
2023-01-18T11:22:52.0718692Z ##[section]Starting: Start ADF Triggers
2023-01-18T11:22:52.0877208Z ==============================================================================
2023-01-18T11:22:52.0877857Z Task         : Azure PowerShell
2023-01-18T11:22:52.0878021Z Description  : Run a PowerShell script within an Azure environment
2023-01-18T11:22:52.0878430Z Version      : 5.209.0
2023-01-18T11:22:52.0878579Z Author       : Microsoft Corporation
2023-01-18T11:22:52.0878779Z Help         : https://aka.ms/azurepowershelltroubleshooting
2023-01-18T11:22:52.0879011Z ==============================================================================
2023-01-18T11:22:53.2938749Z Generating script.
2023-01-18T11:22:54.1401544Z ========================== Starting Command Output ===========================
<removed>
2023-01-18T11:22:58.0022250Z ##[warning] Arm-template parameter file path not specified, the script will look for the file in arm-template file path.
2023-01-18T11:22:58.0064857Z Getting triggers
2023-01-18T11:22:58.9703782Z Getting pipelines
2023-01-18T11:23:01.6249277Z Getting datasets
2023-01-18T11:23:02.5713028Z Getting linked services
2023-01-18T11:23:03.2006931Z Getting integration runtimes
2023-01-18T11:23:03.7682079Z Deleting triggers
2023-01-18T11:23:03.7698004Z Deleting pipelines
2023-01-18T11:23:03.7706933Z Deleting dataflows
2023-01-18T11:23:03.7713985Z Deleting datasets
2023-01-18T11:23:03.7722607Z Deleting linked services
2023-01-18T11:23:03.7730626Z Deleting integration runtimes
2023-01-18T11:23:03.8446126Z ##[error] Conversion from JSON failed with error: Unexpected character encountered while parsing value: T. Path 'properties.pipelines[1].parameters.sandbox', line 23, position 21. from Line: 680
2023-01-18T11:23:04.0714254Z ##[error]Conversion from JSON failed with error: Unexpected character encountered while parsing value: T. Path 'properties.pipelines[1].parameters.sandbox', line 23, position 21.
2023-01-18T11:23:04.2782377Z ##[error]PowerShell exited with code '1'.
```

`"sandbox": true` this is the defined property i think this is failing on, like other bools in the factory use.

**Comment by danyarmoski-medsol** [comment]
Having this same issue this our error but same exact thing.  This was working up until about 2 days ago what happened.

##[error] Conversion from JSON failed with error: Unexpected character encountered while parsing value: T. Path 'properties.typeProperties.ignoreEmptyBlobs', line 21, position 26. from Line: 680

**Comment by jcpontet** [comment]
**Same issue:**

> ##[error] Conversion from JSON failed with error: Unexpected character encountered while parsing value: T. Path 'properties.pipelines[0].parameters.IsForceRefreshEnabled'

**ADF Trigger with a Boolean parameter:**

![image](https://user-images.githubusercontent.com/28356483/214117542-6122e965-48e4-4a34-aac3-a43eca91b864.png)


**Azure DevOps agent logs:**

> ==============================================================================
2023-01-23T18:00:17.5053095Z Task         : Azure PowerShell
2023-01-23T18:00:17.5053258Z Description  : Run a PowerShell script within an Azure environment
2023-01-23T18:00:17.5053482Z Version      : 5.209.0
2023-01-23T18:00:17.5053630Z Author       : Microsoft Corporation
2023-01-23T18:00:17.5053821Z Help         : https://aka.ms/azurepowershelltroubleshooting
2023-01-23T18:00:17.5054026Z ==============================================================================
2023-01-23T18:00:18.4103134Z Generating script.
2023-01-23T18:00:18.4721298Z ##[command]"C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -NoProfile -NonInteractive -
2023-01-23T18:00:22.1928990Z Getting triggers
2023-01-23T18:00:22.6502348Z Getting pipelines
2023-01-23T18:00:24.5686896Z Getting datasets
2023-01-23T18:00:25.2811306Z Getting linked services
2023-01-23T18:00:25.9719980Z Getting integration runtimes
2023-01-23T18:00:26.8708622Z Deleting triggers
2023-01-23T18:00:26.8720041Z Deleting pipelines
2023-01-23T18:00:26.8726298Z Deleting dataflows
2023-01-23T18:00:26.8732490Z Deleting datasets
2023-01-23T18:00:26.8738667Z Deleting linked services
2023-01-23T18:00:26.8745980Z Deleting integration runtimes
2023-01-23T18:00:26.8752588Z Deleting ARM deployment ... under resource group: ....
2023-01-23T18:00:34.2521183Z Deployment to be deleted: ARMTemplateForFactory-20230123-180000-3ac9
2023-01-23T18:00:34.7514245Z Deleting deployment: ARMTemplateForFactory-20230123-180000-3ac9
2023-01-23T18:00:50.5698832Z True
2023-01-23T18:00:50.7625920Z ##[error] Conversion from JSON failed with error: Unexpected character encountered while parsing value: T. Path 'properties.pipelines[0].parameters.IsForceRefreshEnabled', line 15, position 35. from Line: 680
2023-01-23T18:00:50.9932135Z ##[error]Conversion from JSON failed with error: Unexpected character encountered while parsing value: T. Path 'properties.pipelines[0].parameters.IsForceRefreshEnabled', line 15, position 35.
2023-01-23T18:00:51.1160160Z ##[error]PowerShell exited with code '1'.
2023-01-23T18:00:51.3368955Z Added TLS 1.2 in session.

**Comment by MahaSPR** [comment]
I am getting the same error, please help resolve it ASAP, it's blocking our production ADF deployments. Thanks in advance.

2023-01-25T22:47:24.3941272Z ##[section]Starting: Azure PowerShell script: post-deployment task
2023-01-25T22:47:24.4167480Z ==============================================================================
2023-01-25T22:47:24.4168009Z Task         : Azure PowerShell
2023-01-25T22:47:24.4168149Z Description  : Run a PowerShell script within an Azure environment
2023-01-25T22:47:24.4168371Z Version      : 5.216.2
2023-01-25T22:47:24.4168500Z Author       : Microsoft Corporation
2023-01-25T22:47:24.4168832Z Help         : https://aka.ms/azurepowershelltroubleshooting
2023-01-25T22:47:24.4169039Z ==============================================================================
2023-01-25T22:47:25.8364603Z Generating script.
2023-01-25T22:47:25.8983039Z ========================== Starting Command Output ===========================
2023-01-25T22:47:25.9401653Z ##[command]"C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\eea85849-d191-402d-b9fc-09f4628884b8.ps1'"
2023-01-25T22:47:27.2074438Z Added TLS 1.2 in session.
2023-01-25T22:47:27.3078707Z ##[command]Import-Module -Name C:\Modules\az_9.3.0\Az.Accounts\2.11.1\Az.Accounts.psd1 -Global
2023-01-25T22:47:27.5113411Z [33;1mWARNING: Both Az and AzureRM modules were detected on this machine. Az and AzureRM modules cannot be imported in the same session or used in the same script or runbook. If you are running PowerShell in an environment you control you can use the 'Uninstall-AzureRm' cmdlet to remove all AzureRm modules from your machine. If you are running in Azure Automation, take care that none of your runbooks import both Az and AzureRM modules. More information can be found here: https://aka.ms/azps-migration-guide[0m
2023-01-25T22:47:27.8634231Z ##[command]Clear-AzContext -Scope CurrentUser -Force -ErrorAction SilentlyContinue
2023-01-25T22:47:28.1960759Z ##[command]Clear-AzContext -Scope Process
2023-01-25T22:47:28.4893530Z ##[command]Connect-AzAccount -ServicePrincipal -Tenant 201746df-108c-4f4c-8e44-e814f9857eff -Credential System.Management.Automation.PSCredential -Environment AzureCloud @processScope
2023-01-25T22:47:30.5002159Z ##[command] Set-AzContext -SubscriptionId d5e4966a-9beb-46e0-9ab2-516ab5da695e -TenantId 201746df-108c-4f4c-8e44-e814f9857eff
2023-01-25T22:47:31.6074776Z ##[warning] Arm-template parameter file path not specified, the script will look for the file in arm-template file path.
2023-01-25T22:47:31.6235922Z Getting triggers
2023-01-25T22:47:32.4493678Z Getting pipelines
2023-01-25T22:47:35.2031535Z Getting datasets
2023-01-25T22:47:36.1021927Z Getting linked services
2023-01-25T22:47:36.8076466Z Getting integration runtimes
2023-01-25T22:47:37.3445879Z Deleting triggers
2023-01-25T22:47:37.3493870Z Deleting pipelines
2023-01-25T22:47:37.3515287Z Deleting dataflows
2023-01-25T22:47:37.3534002Z Deleting datasets
2023-01-25T22:47:37.3556442Z Deleting linked services
2023-01-25T22:47:37.3674060Z Deleting integration runtimes
2023-01-25T22:47:37.3694703Z Deleting ARM deployment ... under resource group: Accel-Prod-Group
2023-01-25T22:47:43.3750039Z Deployment to be deleted: ARMTemplateForFactory-20230125-224700-5e16
2023-01-25T22:47:43.7570009Z Deleting deployment: ARMTemplateForFactory-20230125-224700-5e16
2023-01-25T22:47:59.6870651Z True
2023-01-25T22:48:00.1331279Z ##[error] Conversion from JSON failed with error: After parsing a value an unexpected character was encountered: ". Path 'properties.pipelines[0].parameters.Body', line 20, position 20. from Line: 680
2023-01-25T22:48:00.2795914Z ##[error]Conversion from JSON failed with error: After parsing a value an unexpected character was encountered: ". Path 'properties.pipelines[0].parameters.Body', line 20, position 20.
2023-01-25T22:48:00.4041223Z ##[error]PowerShell exited with code '1'.
2023-01-25T22:48:00.6273392Z Added TLS 1.2 in session.
2023-01-25T22:48:01.7736614Z ##[section]Finishing: Azure PowerShell script: post-deployment task

**Comment by MahaSPR** [comment]
Also, note that this script is stopping all triggers even if they have not changed compared to the version being deployed. This issue needs to be fixed as well.

**Comment by soma-ms** [comment]
@mahen83, It will be rolled out to node package by 2/16

**Comment by itstushargarg** [comment]
@soma-ms, the issue seems to still exist. 
We are using _microsoft/azure-data-factory-utilities_ package.
As communicated by you, it was supposed to be fixed by 2/16 but the issue still exists. 
Please can you share the current status and by when are we expecting it to be available in this node package.

**Comment by soma-ms** [comment]
@itstushargarg - The fix has been pushed to npm package path on 2/17 due to minor delay in the deployment train. Could you share script execution log to check why the fix is not working. And also share the package.json to check the package configuration.
PS: If using the npm package for Synapse, you may have to wait for another week for the fix to roll out.

**Comment by itstushargarg** [comment]
![image](https://user-images.githubusercontent.com/24522666/220601251-6e8236eb-b484-4bdf-9715-7a3a653e1b74.png)
[package.zip](https://github.com/Azure/Azure-DataFactory/files/10802985/package.zip)

**Comment by itstushargarg** [comment]
@soma-ms, please let me know if you see anything different from expected. The build still continues to fail.

**Comment by itstushargarg** [comment]
Just wanted to update, this has been fixed for me couple of weeks back. Thanks! :)
